import json
from web3 import Web3
import os

# Configuration
GANACHE_URL = "http://127.0.0.1:8545"  # Default Ganache RPC URL
ABI_FILE_PATH = "DIDRegistry.abi.json"
BYTECODE_FILE_PATH = "DIDRegistry.bytecode.txt"
CONTRACT_ADDRESS_FILE = "DIDRegistry.address.txt"

def deploy_contract():
    """
    Connects to Ganache, deploys the DIDRegistry contract, and saves its address.
    """
    # 1. Connect to Ganache
    w3 = Web3(Web3.HTTPProvider(GANACHE_URL))
    if not w3.is_connected(): # For web3.py v6+, use w3.is_listening() or just try a request
        try:
            w3.eth.block_number # Try a simple request to check connection
            print(f"Successfully connected to Ganache at {GANACHE_URL} (via request).")
        except Exception as e:
            print(f"Failed to connect to Ganache at {GANACHE_URL}. Error: {e}")
            print("Please ensure Ganache is running.")
            return False
    else: # For older web3.py versions that have is_connected()
         print(f"Successfully connected to Ganache at {GANACHE_URL} (via is_connected()).")


    # 2. Set a default account (deployer) - use the first account from Ganache
    try:
        w3.eth.default_account = w3.eth.accounts[0]
        deployer_account = w3.eth.default_account
        print(f"Using deployer account: {deployer_account}")
    except Exception as e:
        print(f"Failed to get accounts from Ganache. Ensure Ganache is running with accounts. Error: {e}")
        return False

    # 3. Load ABI and Bytecode
    if not os.path.exists(ABI_FILE_PATH):
        print(f"Error: ABI file not found at {ABI_FILE_PATH}")
        return False
    if not os.path.exists(BYTECODE_FILE_PATH):
        print(f"Error: Bytecode file not found at {BYTECODE_FILE_PATH}")
        return False

    with open(ABI_FILE_PATH, 'r') as f:
        abi = json.load(f)
    with open(BYTECODE_FILE_PATH, 'r') as f:
        bytecode = f.read().strip()

    if not abi or not bytecode:
        print("Error: ABI or bytecode is empty. Please check the compilation output.")
        return False

    # 4. Deploy the contract
    DIDRegistryContract = w3.eth.contract(abi=abi, bytecode=bytecode)

    print("Deploying DIDRegistry contract...")
    try:
        tx_hash = DIDRegistryContract.constructor().transact()
        print(f"Transaction hash: {w3.to_hex(tx_hash)}")

        # 5. Wait for the transaction to be mined
        print("Waiting for transaction to be mined...")
        tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
        
        contract_address = tx_receipt.contractAddress
        if contract_address:
            print(f"DIDRegistry contract deployed successfully!")
            print(f"Contract Address: {contract_address}")

            # 6. Save the contract address to a file
            with open(CONTRACT_ADDRESS_FILE, 'w') as f:
                f.write(contract_address)
            print(f"Contract address saved to {CONTRACT_ADDRESS_FILE}")
            return True
        else:
            print("Error: Contract deployment failed, no contract address in receipt.")
            print(f"Full transaction receipt: {tx_receipt}")
            return False

    except Exception as e:
        print(f"An error occurred during contract deployment: {e}")
        return False

if __name__ == "__main__":
    print("--- Aegis Forge: DIDRegistry Contract Deployment Script ---")
    print("Prerequisites:")
    print("1. Ensure Ganache is running (e.g., `ganache` or `ganache-cli` in another terminal).")
    print("2. Ensure `web3.py` is installed (`pip install web3`).")
    print("3. Ensure `DIDRegistry.abi.json` and `DIDRegistry.bytecode.txt` are present (generated by `compile_and_extract.py`).")
    print("-" * 60)
    
    if deploy_contract():
        print("\nDeployment script finished successfully.")
    else:
        print("\nDeployment script encountered errors.")
